name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: phpunit
    - name: Run
      run: phpunit --configuration test/phpunit.xml
